
class Alignment:
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self) -> None:
        ...
    def __init(self, header: str, fwd: bool, start: int, pres_frac: float, qry_len: int) -> None:
        ...
    @property
    def ctg(self) -> str:
        ...
    @property
    def r_st(self) -> int:
        ...
    @property
    def r_en(self) -> int:
        ...
    @property
    def strand(self) -> int:
        ...
    @property
    def pres_frac(self) -> float:
        ...

class Index:
    @staticmethod
    def _pybind11_conduit_v1_(*args, **kwargs):
        ...
    def __init__(self, input: str, k: int = 15, fwd_reverse: bool = True, jaccard = True) -> None:
        ...
    def dump(self, basename: str) -> None:
        ...
    def query(self, sequence: str) -> Alignment:
        ...
    def query_batch(self, sequences: list[str]) -> list[Alignment]:
        ...
